[build]
  command = "echo 'No build step required'" # No necesitamos un comando de build
  publish = "public" # Servir archivos estáticos desde esta carpeta

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/import-json"
  to = "/.netlify/functions/import-json"
  status = 200