[build]
  command = "echo 'No build step required'" # Usamos un comando que no falla
  publish = "public"

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = "/import-json"
  to = "/.netlify/functions/import-json"
  status = 200